jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
    metadata:
        directories:
            KnpPaginatorBundle:
                namespace_prefix: 'Knp\Bundle\PaginatorBundle'
                path: '%kernel.root_dir%/../config/serializer/KnpPaginatorBundle'
            KnpPager:
                namespace_prefix: 'Knp\Component\Pager'
                path: '%kernel.root_dir%/../config/serializer/KnpPager'
    handlers:
        datetime:
            default_format: "Y-m-d"
            default_timezone: "UTC"
