version:  '3.3'
services:
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_PASSWORD: pwd_api
      MYSQL_USER: api_test
      MYSQL_DATABASE: bdd_test_place2swap
      MYSQL_ROOT_PASSWORD: pwd_root
    command: ["--default-authentication-plugin=mysql_native_password"]

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - './apps/symfony-app/public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php


  node:
    build: docker/node
    volumes:
      - './apps/symfony-app:/usr/src/app'
    command: bash -c "yarn && yarn dev"
